name: Historic
on: workflow_dispatch
permissions:
  contents: read
jobs:
  historic:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        version:
          [
                                                            2008, 2009,
            2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
            2020, 2021, 2022
          ]
        exclude:
          - { os: macos, version: 2008 }
          - { os: macos, version: 2009 }
          - { os: macos, version: 2010 }
          - { os: macos, version: 2011 }
          - { os: macos, version: 2012 }
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          version: ${{ matrix.version }}
